//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoPhones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone
    {
        public int id { get; set; }
        public string idUser { get; set; }
        public string number { get; set; }
        public string balance { get; set; }
        public string status { get; set; }
        public string isPublic { get; set; }
    }
}
