//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoPhones.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class twoPhonesEntities1 : DbContext
    {
        public twoPhonesEntities1()
            : base("name=twoPhonesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cState> cStates { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<phone> phones { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
